### ISSUE TITLE
Wrong character sequence

### ISSUE THREAD

**Issue by mad-rain** [Konash/arabic-support-unity#15]
Hi!

I have a problem with ArabicFixer. This is an original text:

.لطفا با من بشمارید 1 – 2 – 3 – 4 – 5 – 6 – 7 – 8- 9 -10 آفرین! همه چیز صحیح است

This is what we got after Fix:

ﺖﺳا ﺢیﺤﺻ ﺰیﭼ ﻪﻤﻫ !ﻦیﺮﻓآ -10 9 8- – 7 – 6 – 5 – 4 – 3 – 2 – 1 ﺪیرﺎﻤﺸﺑ ﻦﻣ ﺎﺑ ﺎﻔﻄﻟ.

Something is wrong with dashes between 7 and 10. Could you please check?

I have no knowledge of Arabic, but this looks like a bug.

Andrew.

**Comment by rrenperry** [comment]
You have different characters for dash – and -
Also the spacing is different from 1-7 than 8-10
If you change 8-10 to the same format as 1-7 you should be ok
