### ISSUE TITLE
In °س, Seen gets converted to 'end' type

### ISSUE THREAD

**Issue by rrenperry** [Konash/arabic-support-unity#16]
°C in Arabic (as far as I know) °س  is displaying the end contextual form for Seen character but should show the general or isolated form.

**Comment by Konash** [comment]
So aside from the fact that you should use "tashkeel" ° AFTER the letter. it is still broke it. Thanks for the notice. Will fix it now.

**Comment by Konash** [comment]
It seems I never supported the "Sokoon" tashkeel before. Hopefully this should be easy.

**Comment by Konash** [comment]
Ok after some research. It turns out everything is actually working as intended. Sokoon (or Sukun) is actually supported.
The character you gave me in the sample is NOT Sokoon. ° This might be the degree sign? I'm not sure but it is not Sokoon.
THIS is Sokoon: ﹾ and it works fine :)

**Comment by rrenperry** [comment]
Hi Konash,

Sorry I wasn't totally clear - I am trying to display the degree sign, if you see here: https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation
I'm trying to display the sign for degrees Celsius, which is what creates the above issue
