### ISSUE TITLE
In س°, Seen gets converted to 'end' type

### ISSUE THREAD

**Issue by rrenperry** [Konash/arabic-support-unity#18]
Sorry to raise this again but it's not fixed and the issue was misunderstood before...

س° is displaying the end contextual form for Seen character but should show the general or isolated form.

![capture](https://user-images.githubusercontent.com/370601/31879238-bde0a17c-b7d4-11e7-8c86-dfcb0dd3008d.PNG)

Expecting:
![capture2](https://user-images.githubusercontent.com/370601/31879363-22ee5b7c-b7d5-11e7-8098-c415af48b69f.PNG)

Getting:
![capture3](https://user-images.githubusercontent.com/370601/31879369-25514f14-b7d5-11e7-8d96-409b69f332e3.PNG)

If you see here: https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation

I'm trying to display the sign for degrees Celsius, which is what creates the above/attached issue.

**Comment by Konash** [comment]
![degree](https://user-images.githubusercontent.com/12271954/32201468-94f7fa06-bdad-11e7-9ddb-da770e7bb806.jpg)


It is working fine. Did you update to the latest version?

**Comment by rrenperry** [comment]
I just downloaded the latest from here, opened a brand new project and it doesn't work still, are you testing the correct text? 

from https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation

degree Celsius | °C

![image](https://user-images.githubusercontent.com/370601/32326546-245a696c-bfcb-11e7-911f-339350575f2f.png)


![image](https://user-images.githubusercontent.com/370601/32326529-106d699a-bfcb-11e7-9927-759820d05de8.png)

**Comment by rrenperry** [comment]
The degree symbol on your 'fixed' text is at the wrong end...

**Comment by Konash** [comment]
I got you. I'll move the discussion here: https://github.com/Konash/arabic-support-unity/issues/20#issuecomment-341417412
