### ISSUE TITLE
"!" wasn't putted on the end line

### ISSUE THREAD

**Issue by WhiteDambi** [Konash/arabic-support-unity#19]
Hello, this is Stefan who sent the email yesterday. 
I did the test as your recommend that is using last version.

test text :
البحث عن تحديات أكبر في دوريات أعلى!

![test](https://user-images.githubusercontent.com/18730534/32258760-cd94e4e8-beff-11e7-811d-7bd38395e2c0.png)

copy output text and paste to NGUI label

![test1](https://user-images.githubusercontent.com/18730534/32258777-f14cde22-beff-11e7-8dd2-1318a68a85a6.png)

Sorry, I "totally" don't know Arabic at all, so I could not check whether result is correct or not
But even i don't know, but i think "!" should be putted on the final sentence, am i correct ?

**Comment by Konash** [comment]
This is really weird. I copied and pasted your text and this was the result:

![image](https://user-images.githubusercontent.com/12271954/32260024-51e38cdc-be9b-11e7-9cbf-7e502549d989.png)

Do you think it have to do with the device default language? It shouldn't!

Try adding a space between the last word and the ! mark. will it do the same?

**Comment by Konash** [comment]
Are you still facing the issue? Can someone else test this?

**Comment by rrenperry** [comment]
Win10 - English default language - Unity 5.6.0f3

Works fine:
![image](https://user-images.githubusercontent.com/370601/32335791-964d9dcc-bfe5-11e7-9ccd-6456a10d5cfd.png)

**Comment by rrenperry** [comment]
@trident667 are you using TextMesh Pro?

edit: reread your post, using NGUI, never mind!

**Comment by WhiteDambi** [comment]
Win10- Republic of korea default language - Unity 5.6.3f1

It seems to be a default language problem.

Changing the default language from Unity works fine.

I don't use TextMesh Pro.

**Comment by Konash** [comment]
Does this mean we are good?

**Comment by WhiteDambi** [comment]
Sorry to late response.
I'll try to find solution during this weekend. 
Then I'll ask you few qestions.

**Comment by WhiteDambi** [comment]
I am so sorry.
my fault..
your code do not have bug.
