### ISSUE TITLE
In س°, Seen gets converted to 'end' type

### ISSUE THREAD

**Issue by rrenperry** [Konash/arabic-support-unity#20]
Sorry I know this is annoying but we are totally misunderstanding each other I think.

I just downloaded the latest from here, opened a brand new project and it doesn't work still, are you testing the correct text?

from https://en.wikipedia.org/wiki/Modern_Arabic_mathematical_notation

degree Celsius | °C

![image](https://user-images.githubusercontent.com/370601/32326546-245a696c-bfcb-11e7-911f-339350575f2f.png)

![image](https://user-images.githubusercontent.com/370601/32326529-106d699a-bfcb-11e7-9927-759820d05de8.png)

In your response here:
![degree](https://user-images.githubusercontent.com/12271954/32201468-94f7fa06-bdad-11e7-9ddb-da770e7bb806.jpg)

You have the degree symbol the wrong side of the Seen, it should be after (before in rtl) the Seen after it is fixed

Just to be clear I am trying to display the standard degrees symbol 0x00b0, Sokoon is not what I need to display.

**Comment by MohHeader** [comment]
@darrencperry ,,, 
I tried your issue,, & it is working fine here too.

<img width="729" alt="screen shot 2017-11-02 at 4 15 38 pm" src="https://user-images.githubusercontent.com/3213925/32327890-c82542dc-bfe0-11e7-806d-fbdbefb75e56.png">
Here is the text I used : 
درجة الحرارة °س

**Comment by Konash** [comment]
Same old issue: https://github.com/Konash/arabic-support-unity/issues/18#issuecomment-341409506

**Comment by Konash** [comment]
When I change the location of the degree sign, it broke.

![image](https://user-images.githubusercontent.com/12271954/32330761-7dd5c6ee-bfb7-11e7-8b06-b6a9e88212d8.png)

This is the result if I put س on both ends of the degree sign:

![image](https://user-images.githubusercontent.com/12271954/32330789-917e4ad6-bfb7-11e7-9d81-6a40315a510b.png)

**Comment by Konash** [comment]
Fixed :) 

![image](https://user-images.githubusercontent.com/12271954/32331179-a1d00f54-bfb8-11e7-98e4-d7d80dc99dfc.png)

**Comment by rrenperry** [comment]
Thanks Konash! 👍
