### ISSUE TITLE
a lettler is display error

### ISSUE THREAD

**Issue by yingnierxiao** [Konash/arabic-support-unity#26]
One character displays an error in a custom nested font，eg.غلى .The last letter is displayed as the default font in the system font.i see code 64509 is right,but display is error

**Comment by Konash** [comment]
It looks fine here:
![image](https://user-images.githubusercontent.com/12271954/48976978-1e636a00-f0a2-11e8-9efa-afaddac32779.png)
Can share a screenshot of the problem?

I will close for now. Please reopen again with the screenshot.
