### ISSUE TITLE
Multibyte languages are erroneously judged.

### ISSUE THREAD

**Issue by ataihei** [Konash/arabic-support-unity#30]
In multibyte languages (Japanese, Hangul, etc.), it is often LtR, but it is judged as RtL.

Expect
>  日本語は左から右に読む

Actual
>  む読に右らか左は語本日

Can I fix it?

**Comment by Konash** [comment]
I believe that if you add them to the ignore range then it cam be fixed. Or
just do not use the plugin on them. I personally only use the plugin on
Arabic text.
