### ISSUE TITLE
Numbers and punctuation order changed

### ISSUE THREAD

**Issue by Diamonds0a** [Konash/arabic-support-unity#33]
Hi,

I have the following string: زيادة كل الضرر بنسبة $X1% (+$X2%)
<img width="228" alt="arabic" src="https://user-images.githubusercontent.com/470803/52138874-5091ca80-2603-11e9-8c3d-fd39e9e9dbe3.PNG">

$X1 and $X2 are variables to be replaced by the code with numbers.

The result is a very strange ordering of the punctuation. In addition it is placed at the end for some reason.

**Comment by Diamonds0a** [comment]
Oh, this is the English: Increase all damage by $X1% (+$X2%)

I don't speak Arabic, I had this translated by a consulting company.

**Comment by Diamonds0a** [comment]
I commented out lines 634 through 725 and it seems to have fixed. What are those lines for?

**Comment by Diamonds0a** [comment]
Nm that broke other strings.

**Comment by Diamonds0a** [comment]
Ok fixed it. In the lines 634 through 725, I removed numberList.Add() and replaced with with list.Add()

**Comment by Diamonds0a** [comment]
nm not fixed. I see what the code is doing, its making english words in the correct order

**Comment by obahareth** [comment]
Usually rendering engines mess up when you include RTL/LTR in the same text element, I'm not sure the library is responsible for that. This might be a bit different than what you wanted but using [Eastern Arabic Numerals](https://www.wikiwand.com/en/Eastern_Arabic_numerals) might help you fix this.

**Comment by Konash** [comment]
Most likely this is because the plugin is flipping the variable $X1 to 1X$
so that it can be mixed with Arabic. I recommend splitting those variables
and only correct the Arabic strings. Or... just write them like 1X$ instead!
