### ISSUE TITLE
string parameters

### ISSUE THREAD

**Issue by mcolombo** [Konash/arabic-support-unity#39]
Hi, 

On some of our translations, we use parameters for the strings, for example:
رونش ! صديقي العزيز ! لازلنا أصدقاء لمدة تتجاوز {0} سنة

But the filter is removing them.
Is there a way to leave the parameter intact but also use the filter?

Thanks a lot

**Comment by Konash** [comment]
Use the fix AFTER adding what you will replace with the {0}.
