### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by asashour** [Konash/arabic-support-unity#40]
Hi all,

With Unity `2019.4.1f1`, there is a compilation error that

> `GameObject` doesn't contain a definition of `guiText`

Which seemed to have been removed in version `5.3.6`.

Can we have an updated plugin please?

**Comment by Konash** [comment]
Hi, you can just download the unity package here:
https://github.com/Konash/arabic-support-unity/blob/master/arabic-support-for-unity.unitypackage
and ignore the sample scene. All you need really in the ArabicSupport.cs
file.
