### ISSUE TITLE
How to use with TMPro RTL enabled?

### ISSUE THREAD

**Issue by elringus** [Konash/arabic-support-unity#41]
Hello @Konash, Thanks for making and maintaining the project! 

I'm developer of [Naninovel](https://naninovel.com) visual novel engine and trying to add Arabic languages support. We're using a [TMPro](https://docs.unity3d.com/Packages/com.unity.textmeshpro@3.0/manual) text component to display the text. It already has RTL languages support and performs characters rearrangement, but our users mentioned, that the letters are disconnected. Here is the result we have when using only TMPro RTL option: 

![](https://i.gyazo.com/a419126ac8fd7d6d73fc3d8e4d5f4ab3.png)

I've tried using this project to fix the disconnection issue like following:

```csharp
// Second (rtl) argument is false, as TMPro handles RTL modification
text = ArabicSupport.ArabicFixer.Fix(text, false);
```

Given the following input (initial `text` value):
مهمانسرای عباسی یا هتل شاه عباس یکی از هتل‌های بزرگ ایران و شهر اصفهان است که به دلیل معماری آن، که از معماری دوران صفوی الگو گرفته است، و نیز واقع شدن آن در میان بافت تاریخی اصفهان دارای اهمیت فراوان است. سی‌ان‌ان در گزارشی در مارس ۲۰۱۷ هتل عباسی را به عنوان زیباترین ه

I'm getting this result (don't mind the "OKUY" part):
![](https://i.gyazo.com/97b10a1c0b5e1d264d69fc9039aaae2b.png)

Unfortunately, I'm not familiar with any Arabic languages, hence it's problematic for me to comprehend what's going on there. I'd really appreciate any hints on how to solve the issue. 

Regards,
Artyom.

**Comment by Konash** [comment]
Hi!
I think the text contains a lot of none arabic characters that I am not
familiar with. Probably Farsi.

This most likely can be solved if you add the newly letters and follow the
logic of the added characters.

**Comment by obahareth** [comment]
Hey @Elringus, asides from what @Konash mentioned (and the text does indeed seem to be Farsi/Persian, not Arabic) you might have some luck if you either:

- Try [UPersian](https://github.com/ElectroGryphon/EGGA/tree/master/UPersian) instead.
- Try [RTLTMPro](https://github.com/mnarimani/RTLTMPro) alongside UPersian. I believe TextMesh Pro introduces a lot of [issues with fonts](https://forum.unity.com/threads/arabic-only-displaying-isolated-forms.528304/) as well so the choice of font might be a factor here as well.

**Comment by elringus** [comment]
Thank you for the fast replies! I've tried the following (hopefully) Arabic text sample:

كن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية. 

But it yields a similar result. I've also noticed, that invoking:

```csharp
// Second (rtl) argument is false, as TMPro handles RTL modification
text = ArabicSupport.ArabicFixer.Fix(text, false);
```

— still rearrange the characters, even though the second (`rtl`) argument is set to false. Is this by design and the `rtl` argument is meant for something else?

**Comment by elringus** [comment]
For example here is an input and result strings, as logged in the console:
```
input: لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية. 
result:  .ﺔﻳﺮﺸﺒﻟا ةدﺎﻌﺴﻟا ﻚﻠﺗ سﺎﺳأو ﺔﻘﻴﻘﺣ ﻒﺸﺘﻜﺘﻟ ﻞﻴﺻﺎﻔﺘﻟا ﻚﻟ ضﺮﻋﺄﺳو ،ﻞﻌﻔﻟﺎﺑ تﺄﺸﻧ ﻢﻟﻷا ﺪﻴﺠﻤﺗو ةﻮﺸﻨﻟا  رﺎﻜﻨﺘﺳا لﻮﺣ ﺔﻃﻮﻠﻐﻤﻟا رﺎﻜﻓﻷا هﺬﻫ ﻞﻛ نأ ﻚﻟ ﺢﺿوأ نأ ﺪﺑ ﻻ ﻦﻜﻟ
```
As you can see `ArabicSupport.ArabicFixer.Fix(text, false)` still change the letters order.

**Comment by elringus** [comment]
I've tried to track where the letters are reordered (to remove that part), but with no luck. Would really appreciate if someone can point to the place in the sources.

**Comment by asashour** [comment]
You last two examples are in Arabic.

Please note the `input` is already correct text (I hope this is what is shown in the console, not due to copy-paste). However, the `result` is inverted.

I would suggest you try this particular text without `ArabicFixer`, and see if the user see exactly the `input`.

Otherwise, please share a minimal project, by which others could investigate further.

**Comment by elringus** [comment]
Thank you for the reply! When the input string is assigned to TMPro, it produce following result:

![](https://i.gyazo.com/12882f7b56ea04d7284d4f85ccc6e0ab.jpg)

I guess it's displayed on GitHub correctly due to browser automatically fixing it.

I've tried invoking `ArabicFixer.Fix()` twice to hopefully reverse the letters order back, but preserve the connection fix (eg `text = ArabicFixer.Fix((ArabicFixer.Fix(text))`, and got the following:

![](https://cdn.discordapp.com/attachments/724274152336392233/729757729748549692/593876977f4e67f86b272f12d2024c31.jpg)

The connection issue seems to be fixed, but I guess the order is still messed up.

Here is the minimal repro project: https://github.com/Elringus/ArabicFixerIssue
The text is modified by ArabicSupport and set to TMPro here: https://github.com/Elringus/ArabicFixerIssue/blob/master/Assets/Runtime/SetArabicText.cs

**Comment by Konash** [comment]
Somehow, this plugin helps. It does not produce the problem mentioned
above:
http://www.inter-illusion.com/assets/I2LocalizationManual/I2LocalizationManual.html
I personally use it. Highly recommended.

Generally your goal is to make the text in the field like the below image:

[image: image.png]

**Comment by elringus** [comment]
I've purchased that asset to check how they handle RTL, but it's an exact copy-paste from your ArabicFixer, just under another namespace and class name...

**Comment by elringus** [comment]
I feel this could be solved if I just find a way to prevent ArabicFixer from flipping (reordering) the letters. 

![](https://i.gyazo.com/641e2ac05c03acda8256f18f6414fa24.jpg)

**Comment by elringus** [comment]
@obahareth Thanks for mentioning [RTLMPro](https://github.com/mnarimani/RTLTMPro)! It solves all the issues (Arabic, Farsi, etc) and has a clean and simple API making it a pleasure to integrate. It also uses a `StringBuilder` instead of multiple string operations, which saves a ton of performance, eg:

```csharp

readonly StringBuilder resultBuilder = new StringBuilder();

void SetText (string text)
{
    resultBuilder.Clear();
    RTLSupport.FixRTL(text, resultBuilder);
    resultBuilder.Reverse();
    tmpro.text = resultBuilder.ToString();
}
```
![](https://i.gyazo.com/6fe0b34505cb92dc130ad433e82a877c.gif)
