### ISSUE TITLE
GUI Text is obselete

### ISSUE THREAD

**Issue by ah1053** [Konash/arabic-support-unity#42]
using UnityEngine.UI;

gameObject.GetComponent<Text>().text = "This sentence (wrong display):\n" + text +
			"\n\nWill appear correctly as:\n" + ArabicFixer.Fix(text, false, false);

Great effort @Konash Chapeau ⭐

**Comment by Waqax19** [comment]
this is not working correctly, still giving errors

**Comment by ah1053** [comment]
gameObject.GetComponent<Text>().text should do it

**Comment by albrrt** [comment]
Same issue here but easy fix, worth upgrading the code for everyone. See my pull request #44

**Comment by ah1053** [comment]
Fixed by @albrrt PR https://github.com/Konash/arabic-support-unity/commit/951492f3302ed78ca2faa9f782b87f7d8690be88
Thanks
