### ISSUE TITLE
HTML tags support

### ISSUE THREAD

**Issue by MohHeader** [Konash/arabic-support-unity#7]
First I would like to thank for this great add-on, I always use it in my arabic projects.

Currently I was working on integrating fungus with Arabic support :
http://fungusgames.com/forum/#!/support-questions:right-to-left-writing-say

I got an issue when I try to Fix( arabic string )
Fungus, use html tags to show & hide letters
So instead of showing the text by adding letters one by one
```
ا
اس
اسم
```

they do it something like this :
```
<color=#FFFFFF00>سم</color>ا
<color=#FFFFFF00>م</color>اس
اسم
```

in this case, the html tag in the fix process got interrupted.

I am trying to fix it, but I believe I may be doing something wrong

Thanks,

**Comment by MohHeader** [comment]
I found some reviews on Unity Assets store page having the same issue.
And I think it is related to ( rich text support ).

**Comment by willnode** [comment]
I also have the same problem. I've developed a way to split characters between LTR and RTL, which means arabic alternation only happen in RTL characters so HTML tags will work.

Have a look here. https://gist.github.com/willnode/f25f4c4fbd1c36da7ee7f9c496a901c7

There, modify everything you don't need and try something like ReplaceString("YourTggedString"). That script is part of my asset TEXDraw which handles RTL stuff. Feel free to use it. @Konash feel free to integrate

**Comment by Konash** [comment]
Thank you @WelloSoft for sharing that code.

@MohHeader did it work for you?

The plugin assumes the input you want to fix is using Arabic characters only. Once you mix other characters things can get tricky. I do recommend you follow Wello's approach.
