### ISSUE TITLE
How can I fix the arabic text in Unity, It looks like broken? 

### ISSUE THREAD

**Issue by handanzhang** [Konash/arabic-support-unity#9]
I do the work for arabic display, but I encounter a problem that the word  is separated. Can you tell me how to fix this problem? Thans for your help
![tim 20170718183320](https://user-images.githubusercontent.com/1832760/28313026-cffd0d48-6be7-11e7-9ca8-2e3f91141a7b.png)

![tim 20170718183303](https://user-images.githubusercontent.com/1832760/28313028-d18b205a-6be7-11e7-8494-e16d642f488e.png)

**Comment by MohHeader** [comment]
You used the plugin method : ArabicSupport.ArabicFixer.Fix() ?

**Comment by handanzhang** [comment]
Yes, I am using it now. Thanks
